### ISSUE TITLE
Peer to Peer code review

### ISSUE THREAD

**Issue by rootDEV2990** [bettercallazamat/event-mgmt-ror#1]
Great job bro! Project looks awesome!! Great job on your controllers from scratch 🙌🏼
Some notes from the team

- Try to follow restful conventions.
- Consider using delete in routes for your method inside of view.
- Use plural form in your through Association and it should be your last line. 

Keep it up bro 🚀

**Comment by bettercallazamat** [comment]
Thanks for feedback, they are applied.
